import Link from 'next/link';
const STEPS=[['Read','An extractor reads each PDF and pulls out values. Every value keeps its page and the exact quote it came from.'],['Decide','A rules engine, written as plain code, compares those values with the buyer\'s rules. No model makes this call.'],['Check','An auditor looks for every quote in the document text. If one is missing it asks for a re-read. It cannot change a verdict.'],['Review','A person approves, edits or rejects. Drafts for the supplier wait in a demo outbox until then.']];
const LIMITS=[['No black-box verdicts','Pass or fail comes from rules anyone can read, not from a language model.'],['Unsupported values stay empty','If a value is not on the page, the field is left blank instead of guessed.'],['Nothing is sent without approval','Messages to suppliers are drafts. The demo outbox never contacts anyone.'],['No accuracy claim','This runs on synthetic documents and a demo framework. We do not report an accuracy figure.']];
export default function Landing(){
  return(<div className="min-h-screen">
    <header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><span className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid h-6 w-6 place-items-center rounded bg-ink text-xs text-paper">C</span>ChainAudit</span>
      <nav className="flex items-center gap-5 text-sm text-mute"><a href="#how" className="hover:text-ink">How it works</a><a href="#limits" className="hover:text-ink">What it does not do</a><Link href="/workflows" className="rounded-md bg-ink px-3 py-1.5 text-paper">Open control center</Link></nav></header>
    <main>
      <section className="mx-auto grid max-w-6xl items-center gap-12 px-6 pb-20 pt-12 lg:grid-cols-[1fr_1.05fr]">
        <div><h1 className="text-5xl font-semibold leading-[1.05] tracking-tight sm:text-6xl">Every compliance decision, traceable to a line on a page.</h1>
          <p className="mt-6 max-w-lg text-lg text-mute">Drop in supplier documents. Agents read them, a rules engine decides, and an independent auditor checks each quote against the page it came from.</p>
          <div className="mt-8 flex flex-wrap gap-3"><Link href="/start" className="rounded-md bg-act px-5 py-2.5 text-sm font-medium text-white">Start an audit</Link><Link href="/workflows" className="rounded-md border border-line bg-card px-5 py-2.5 text-sm">Watch a recorded run</Link></div>
          <p className="mt-4 text-xs text-mute">Runs on synthetic demo data and a demo buyer framework.</p></div>
        <figure aria-label="Example finding" className="relative">
          <div className="rounded-lg border border-line bg-white p-6 font-mono text-xs leading-6 text-[#0E1116] shadow-sm"><div className="flex justify-between text-[#5B6472]"><span>lab_report_BT-2047.pdf</span><span>page 2</span></div>
            <p className="mt-3">TEST REPORT (synthetic demo)</p><p>Supplier ID: SUP-002</p><p>Batch ID: BT-2047</p><p className="pulse-bad -mx-2 rounded bg-warn/30 px-2">Chemical concentration 17.4 ppm</p></div>
          <div className="ml-8 h-5 border-l-2 border-dashed border-line" aria-hidden/>
          <div className="rounded-lg border border-bad/40 bg-bad/10 p-4"><div className="text-sm font-medium text-bad">Requirement not satisfied</div><p className="mt-1 text-sm">17.4 ppm exceeds the configured maximum of 15 ppm.</p>
            <ul className="mt-3 space-y-1 text-xs text-mute"><li className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-ok"/>Auditor: quote found in the document, page 2</li><li className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-warn"/>Reviewer: waiting for a decision</li></ul></div>
          <figcaption className="mt-2 text-xs text-mute">Illustration built from the synthetic demo report.</figcaption></figure></section>
      <section id="how" className="border-y border-line bg-card"><div className="mx-auto max-w-6xl px-6 py-16"><h2 className="text-2xl font-semibold tracking-tight">How a document becomes a finding</h2>
        <ol className="mt-8 grid gap-6 md:grid-cols-4">{STEPS.map(([t,d],i)=><li key={t}><div className="font-mono text-sm text-act">{i+1}</div><h3 className="mt-1 font-medium">{t}</h3><p className="mt-1 text-sm text-mute">{d}</p></li>)}</ol></div></section>
      <section id="limits" className="mx-auto max-w-6xl px-6 py-16"><h2 className="text-2xl font-semibold tracking-tight">Built to be doubted</h2><p className="mt-2 max-w-xl text-mute">A judge, a buyer or a supplier should be able to challenge any result. These rules make that possible.</p>
        <dl className="mt-8 grid gap-x-12 gap-y-6 md:grid-cols-2">{LIMITS.map(([t,d])=><div key={t}><dt className="font-medium">{t}</dt><dd className="mt-1 text-sm text-mute">{d}</dd></div>)}</dl>
        <div className="mt-12 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-line bg-card p-6"><div><div className="font-medium">See it run end to end</div><div className="text-sm text-mute">Replay a recorded audit or upload your own sample PDFs.</div></div><Link href="/start" className="rounded-md bg-ink px-5 py-2.5 text-sm text-paper">Start an audit</Link></div></section></main>
    <footer className="border-t border-line px-6 py-6 text-center text-xs text-mute">ChainAudit control center. Synthetic Demo Data · Demo Buyer Framework v1.0. AI drafts always need review before sending.</footer></div>)}
