'use client';
import Link from 'next/link';import {useQuery} from '@tanstack/react-query';import {api,MOCK,REPLAYS,REPLAY_INFO} from '@/lib/api';import {TrustStrip} from '@/components/trust-strip';
type W={workflow_id:string;status:string;created_at:string;document_count:number;finding_count:number;needs_review_count:number;replay:boolean};
const chip=(s:string)=>s==='COMPLETED'?'border-ok/40 bg-ok/10 text-ok':s==='FAILED'?'border-bad/40 bg-bad/10 text-bad':s==='AWAITING_REVIEW'?'border-warn/50 bg-warn/10 text-warn':'border-line text-mute';
const SAMPLE:Record<string,string>={failed_supplier:'Needs review',clean_supplier:'All passing',auditor_loop_fault_injection:'Test mode',decoy_trap_fault_injection:'Test mode'};
export default function Overview(){
  const q=useQuery<W[]>({queryKey:['workflows'],queryFn:()=>api<W[]>('/workflows'),enabled:!MOCK});const rows=q.data??[];const n=(f:(w:W)=>number)=>rows.reduce((a,w)=>a+f(w),0);
  return(<><TrustStrip/><main className="mx-auto max-w-5xl px-6 py-8">
    <div className="mb-6 flex items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">Overview</h1><p className="text-sm text-mute">Audit runs on this device. Numbers come from synthetic data.</p></div><Link href="/start" className="rounded-md bg-act px-4 py-2 text-sm font-medium text-white">New audit</Link></div>
    {!MOCK&&rows.length>0&&<dl className="mb-6 grid grid-cols-3 gap-3">{[['Runs',rows.length],['Findings',n(w=>w.finding_count)],['Waiting for review',n(w=>w.needs_review_count)]].map(([k,v])=><div key={k as string} className="rounded-xl border border-line bg-card p-4"><dt className="text-xs text-mute">{k}</dt><dd className="mt-1 text-3xl font-semibold tracking-tight">{v}</dd></div>)}</dl>}
    <h2 className="mb-2 text-sm font-medium text-mute">{MOCK||q.isError?'Recorded runs':'Recent runs'}</h2>
    {MOCK||q.isError?<ul className="divide-y divide-line rounded-xl border border-line bg-card">{REPLAYS.map(r=><li key={r} className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 text-sm"><span className="min-w-0 flex-1">{REPLAY_INFO[r]}</span><span className={`rounded-full border px-2.5 py-0.5 text-xs ${r==='clean_supplier'?chip('COMPLETED'):r==='failed_supplier'?chip('AWAITING_REVIEW'):chip('')}`}>{SAMPLE[r]}</span><span className="flex gap-4"><Link className="text-act" href={`/workflows/mock-${r}`}>Open run</Link><Link className="text-act" href={`/audit/mock-${r}`}>Audit record</Link></span></li>)}</ul>
    :q.isLoading?<p className="text-sm text-mute">Loading…</p>
    :!rows.length?<div className="rounded-xl border border-dashed border-line p-10 text-center"><p className="font-medium">No audits yet</p><p className="mt-1 text-sm text-mute">Upload supplier PDFs or play a recorded run to see the agents work.</p><Link href="/start" className="mt-4 inline-block text-sm text-act">Start an audit</Link></div>
    :<ul className="divide-y divide-line rounded-xl border border-line bg-card">{rows.map(w=><li key={w.workflow_id} className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 text-sm"><span className="font-mono text-xs">{w.workflow_id}</span><span className="text-xs text-mute">{w.document_count} documents · {w.finding_count} findings</span><span className={`rounded-full border px-2.5 py-0.5 text-xs ${chip(w.status)}`}>{w.status.replace('_',' ').toLowerCase()}{w.replay?' · replay':''}</span><span className="flex gap-4"><Link className="text-act" href={`/workflows/${w.workflow_id}`}>Open run</Link><Link className="text-act" href={`/audit/${w.workflow_id}`}>Audit record</Link></span></li>)}</ul>}
  {!MOCK&&q.isError&&<p role="status" className="mt-3 text-xs text-mute">The live backend is not reachable right now (free hosting may be asleep). Recorded runs above still work.</p>}
  </main></>)}
